### ISSUE TITLE
Error during registartion

### ISSUE THREAD

**Issue by anLizard** [tectiv3/standardfile#20] opened 2019-03-18 15:10 UTC
I managed to get the server running on port 8888 on my server, which can be accessed thanks to the reverse proxy on Apache. Visiting `https://sn.domain.com` on Chrome shows me `Dashboard. Server version: dev`. SSL certificate is working as intended.

But when registering on https://app.standardnotes.org/, I get the message `A server error occurred while trying to register. Please try again.`.

This is what the Chrome console tells me:

```
OPTIONS https://sn.domain.ocm/auth net::ERR_ABORTED 404 (Not Found)
```
[...]
```
Access to XMLHttpRequest at 'https://sn.domain.com/auth' from origin 'https://app.standardnotes.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by tectiv3** [comment] 2019-03-19 02:50
Try to set server url in SN as `https://sn.domain.com/api/`

**Comment by anLizard** [comment] 2019-03-19 09:22
Still getting the same error. Here's some extra info.
I'm using a standardfile.json config, made using your template:
```
{
    "port": 24001,
    "foreground": true,
    "debug": false,
    "socket": "",
    "noreg": false,
    "cors": true,
    "db": "sf.db"
}
```

The apache reverse proxy is setup using this site.conf:
```
<VirtualHost *:80>
        ServerName sn.domain.com
        Redirect / https://sn.domain.com/
</VirtualHost>

<VirtualHost *:443>
        ServerName sn.domain.com
        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/sn.lzrd.org/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/sn.lzrd.org/privkey.pem

        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:24001/
        ProxyPassReverse / http://127.0.0.1:24001/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by tectiv3** [comment] 2019-03-19 09:25
```
OPTIONS https://sn.domain.ocm/auth net::ERR_ABORTED 404 (Not Found)
```
Same error?

It should request `https://sn.domain.ocm/api/auth`

**Comment by anLizard** [comment] 2019-03-19 09:30
Getting very similar errors when using the different url.
```
Failed to load resource: the server responded with a status of 404 (Not Found) sn.domain.com/api/auth:1
```
```
Access to XMLHttpRequest at 'https://sn.lzrd.org/api/auth' from origin 'https://app.standardnotes.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Here's some extra info.
I'm using a standardfile.json config, made using your template:
```
{
    "port": 24001,
    "foreground": true,
    "debug": false,
    "socket": "",
    "noreg": false,
    "cors": true,
    "db": "sf.db"
}
```

The reverse proxy is setup using this sn.domain.com.conf. It is enabled in apache:
```
<VirtualHost *:80>
        ServerName sn.domain.com
        Redirect / https://sn.domain.com/
</VirtualHost>

<VirtualHost *:443>
        ServerName sn.domain.com
        SSLEngine on
        SSLCertificateFile /etc/letsencrypt/live/sn.lzrd.org/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/sn.lzrd.org/privkey.pem

        ProxyPreserveHost On
        ProxyPass / http://127.0.0.1:24001/
        ProxyPassReverse / http://127.0.0.1:24001/
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by tectiv3** [comment] 2019-03-19 09:42
Hey, can you go to `https://sn.domain.com/api/auth/params?email=test@test.com` and tell me what you see? If it outputs json error - then api is working correctly. If not - check your webserver. Sorry I am not that familiar with apache proxy syntax to point any errors.

**Comment by tectiv3** [comment] 2019-03-19 09:43
I also would suggest using nginx or caddy instead of apache. Both are more lightweight and performant.

**Comment by anLizard** [comment] 2019-03-19 10:26
I managed to fix the problem.
Apache wasn't configured to handle CORS.
After `a2enmod headers` and adding these lines to the VirtualHost, registration worked using the /api url. Notes saved as well.

```
Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS"
Header always set Access-Control-Allow-Headers "append, delete, entries, foreach, get, has, keys, set, values, Authorization, Origin, X-Requested-With, Content-Type, Accept"
RewriteEngine On
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]
```

**Comment by anLizard** [comment] 2019-03-19 10:27
> 
> 
> Hey, can you go to `https://sn.domain.com/api/auth/params?email=test@test.com` and tell me what you see? If it outputs json error - then api is working correctly. If not - check your webserver. Sorry I am not that familiar with apache proxy syntax to point any errors.

This is the output:
```
error |  
-- | --
message | "Invalid email or password"
code | 404
```

**Comment by anLizard** [comment] 2019-03-19 10:29
> 
> 
> I also would suggest using nginx or caddy instead of apache. Both are more lightweight and performant.

I decided to use Apache becasue I had experience with it before, but I might just try out nginx now. I feel like that could have saved me a looooooot of trouble.
Anyway, thanks for your assistance, and MAJOR props to you for making the Go Implementation! I had lots of trouble getting the Ruby one to work to the point that I just gave up, and your version was much easier to initially set up.

**Comment by tectiv3** [comment] 2019-03-19 10:47
Glad it worked out.
Do you mind opening a PR with apache instructions?

**Comment by anLizard** [comment] 2019-03-19 12:07
Sure, I'll have a look. I'm still new to using github for anything that isn't downloading releases.

**Comment by tonymet** [comment] 2019-05-16 17:41
For those getting 404 for `OPTIONS /api/auth` -- the issue is that the `standardnotes.json` config file is not read properly: the `cors` option is ignored. 

Update your file like this, which will enable CORS properly.
```
@@ -4,6 +4,6 @@
     "debug": false,
     "socket": "",
     "noreg": false,
-    "cors": false,
+    "UseCORS": true,
     "db": "sf.db"
 }

```

I tested the other config params (debug, noreg, etc) and those work fine--only `cors` does not read properly. 

I put a break `$GOROOT/go/src/github.com/heetch/confita/backend/file/file.go` L46 and confirmed that `to` is not receiving the `UseCORS` value

@anLizard @tectiv3

**Comment by tectiv3** [comment] 2019-05-17 05:25
Should be fixed now:
```
	UseCORS    bool   `config:"cors" json:"cors" yaml:"cors" toml:"cors"`
```
Thank you!

**Closed as completed** 2019-05-17 05:46 UTC

**Comment by tonymet** [comment] 2019-05-17 16:29
great work thanks!
